version: '3'
services:
  server:
    container_name: server
    build: ./commbServer
    ports:
      - "8080:8080"
  client:
    container_name: client
    build: ./client
    ports:
      - "8000:8000"
    depends_on:
      - server
  nginx:
    container_name: nginx
    # image: proxy
    build: ./.nginx
    depends_on:
      - server
      - client
    volumes:
      - .nginx/conf.d:/etc/nginx/conf.d
      - .nginx/certbot/conf:/etc/nginx/ssl
      - .nginx/certbot/data:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --eamil anstjd9115@gamil.com --agree-tos --no-eff-email -d i5a602.p.ssafy.io
    volumes:
      - .nginx/certbot/conf:/etc/letsencrypt
      - .nginx/certbot/logs:/var/log/letsencrypt
      - .nginx/certbot/data:/var/www/certbot