spring:
  datasource:
    url: jdbc:mysql://i5a602.p.ssafy.io/CommBTest
    username: root
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: commbzomb@gmail.com
    password: ssafy602!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
