# server.port=8081

spring:
  datasource:
    url : jdbc:mysql://i5a602.p.ssafy.io/CommBTest
    username : root
    password : 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: commbzomb@gmail.com
    password: ssafy602!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  redis:
    host : i5a602.p.ssafy.io
    password : 1234
    port : 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 816e60a58fc8adaf01fa27c0bc3ed383
            client-secret: gUfGcX3lSRaX4y1uVNOBrvdr7WIEhy2F
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
            client-authentication-method: POST
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 21MB


security:
  expire:
    accesstoken: 36000000          # 60초 : 60000, # 60분 : 3600000, # 1일 : 86400000, # 7일 : 604800000
    refreshtoken: 604800000
  secretkey: jeignrwlgnreiu5ngd2fdgdqgblwef2epfkwefbedkbvdfk9jk32fdmhgfg
  accesstoken: "accesstoken"
  refreshtoken: "refreshtoken"

mybatis:
  config-location: classpath:/config/mybatis-config.xml

cloud:
  aws:
    credentials:
      accessKey : AKIAW4VCONM6ZDUGJRPK
      secretKey : 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
    s3:
      bucket : ssafy.commb
    region:
      static: ap-northeast-2
    stack:
      auto: false
  profile: "https://s3.ap-northeast-2.amazonaws.com/ssafy.commb/profile/"
  feed : "https://s3.ap-northeast-2.amazonaws.com/ssafy.commb/feed/"
