# server.port=8081

spring:
  datasource:
    url : jdbc:mysql://i5a602.p.ssafy.io/CommBTest
    username : root
    password : 1234

  redis:
    host : 127.0.0.1
    password : 1234
    port : 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 816e60a58fc8adaf01fa27c0bc3ed383
            client-secret: gUfGcX3lSRaX4y1uVNOBrvdr7WIEhy2F
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
            client-authentication-method: POST
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


security:
  expire:
    accesstoken: 60000          # 60초 : 60000, # 60분 : 3600000, # 1일 : 86400000, # 7일 : 604800000
    refreshtoken: 300000
  secretkey: jeignrwlgnreiu5ngd2fdgdqgblwef2epfkwefbedkbvdfk9jk32fdmhgfg
  accesstoken: "access-token"
  refreshtoken: "refresh-token"