# server.port=8081

spring:
  datasource:
    url : jdbc:mysql://i5a602.p.ssafy.io/CommBTest
    username : root
    password : 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: commbzomb@gmail.com
    password: ssafy602!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  redis:
    host : 127.0.0.1
    password : 1234
    port : 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 816e60a58fc8adaf01fa27c0bc3ed383
            client-secret: gUfGcX3lSRaX4y1uVNOBrvdr7WIEhy2F
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
            client-authentication-method: POST
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 21MB


security:
  expire:
    accesstoken: 60000          # 60초 : 60000, # 60분 : 3600000, # 1일 : 86400000, # 7일 : 604800000
    refreshtoken: 300000
  secretkey: jeignrwlgnreiu5ngd2fdgdqgblwef2epfkwefbedkbvdfk9jk32fdmhgfg
  accesstoken: "access-token"
  refreshtoken: "refresh-token"
