# server.port=8081

spring:
  datasource:
    url : jdbc:mysql://i5a602.p.ssafy.io/CommBTest
    username : root
    password : 1234

  redis:
    host : 127.0.0.1
    password : 1234
    port : 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 21MB


security:
  expire:
    accesstoken: 60000          # 60초 : 60000, # 60분 : 3600000, # 1일 : 86400000, # 7일 : 604800000
    refreshtoken: 300000
  secretkey: jeignrwlgnreiu5ngd2fdgdqgblwef2epfkwefbedkbvdfk9jk32fdmhgfg
  accesstoken: "access-token"
  refreshtoken: "refresh-token"
